import {
  AutomationItem,
  BreachListItem,
} from "./widget-automation-content.models";

export const widgetDemoAutomations: AutomationItem[] = [
  {
    id: "1",
    name: "Widget Validate Contacts",
    type: "form",
    breachList: [
      {
        id: "1",
        recordName: "Last Contact 1",
        type: "mine",
        outcome: "passed",
        errorMessage: "",
        details: "All checks passed.",
      },
      {
        id: "2",
        recordName: "Contact 2",
        type: "Teams",
        outcome: "review",
        errorMessage: "Missing phone number.",
        details: "Phone number field is empty.",
      },
      {
        id: "3",
        recordName: "Contact 3",
        type: "mine",
        outcome: "error",
        errorMessage: "Invalid email format.",
        details: "Email does not match required pattern.",
      },
    ],
    dateOfRun: "4/12/25, 8:21 AM",
    status: "running",
    breachListLink: "http://example.com/breach-list",
    testedRecordsCount: 120,
    passedRecordsCount: 120,
    failedRecordsCount: 0,
    failedRecordsWithErrorCount: 0,
  },
  {
    id: "2",
    name: "Widget Validate Contacts",
    type: "form",
    breachList: [
      {
        id: "1",
        recordName: "Contact 1",
        type: "mine",
        outcome: "passed",
        errorMessage: "",
        details: "All checks passed.",
      },
      {
        id: "2",
        recordName: "Contact 2",
        type: "Teams",
        outcome: "review",
        errorMessage: "Missing phone number.",
        details: "Phone number field is empty.",
      },
      {
        id: "3",
        recordName: "Contact 3",
        type: "mine",
        outcome: "error",
        errorMessage: "Invalid email format.",
        details: "Email does not match required pattern.",
      },
    ],
    dateOfRun: "11/3/25, 1:44 PM",
    status: "completed",
    breachListLink: "http://example.com/breach-list",
    testedRecordsCount: 90,
    passedRecordsCount: 5,
    failedRecordsCount: 2,
    failedRecordsWithErrorCount: 0,
  },
  {
    id: "3",
    name: "Widget Validate Contacts",
    type: "form",
    breachList: [
      {
        id: "1",
        recordName: "Contact 1",
        type: "mine",
        outcome: "passed",
        errorMessage: "",
        details: "All checks passed.",
      },
      {
        id: "2",
        recordName: "Contact 2",
        type: "Teams",
        outcome: "review",
        errorMessage: "Missing phone number.",
        details: "Phone number field is empty.",
      },
      {
        id: "3",
        recordName: "Contact 3",
        type: "mine",
        outcome: "error",
        errorMessage: "Invalid email format.",
        details: "Email does not match required pattern.",
      },
    ],
    dateOfRun: "2/27/25, 5:09 PM",
    status: "failed",
    breachListLink: "http://example.com/breach-list",
    testedRecordsCount: 70,
    passedRecordsCount: 30,
    failedRecordsCount: 30,
    failedRecordsWithErrorCount: 10,
  },
  {
    id: "1",
    name: "Widget Validate Contacts",
    type: "form",
    breachList: [
      {
        id: "1",
        recordName: "Contact 1",
        type: "mine",
        outcome: "passed",
        errorMessage: "",
        details: "All checks passed.",
      },
      {
        id: "2",
        recordName: "Contact 2",
        type: "Teams",
        outcome: "review",
        errorMessage: "Missing phone number.",
        details: "Phone number field is empty.",
      },
      {
        id: "3",
        recordName: "Contact 3",
        type: "mine",
        outcome: "error",
        errorMessage: "Invalid email format.",
        details: "Email does not match required pattern.",
      },
    ],
    dateOfRun: "2023-03-15",
    status: "completed",
    breachListLink: "http://example.com/breach-list",
    testedRecordsCount: 100,
    passedRecordsCount: 80,
    failedRecordsCount: 20,
    failedRecordsWithErrorCount: 5,
  },
  {
    id: "1",
    name: "Widget Validate Contacts",
    type: "form",
    breachList: [
      {
        id: "1",
        recordName: "Contact 1",
        type: "mine",
        outcome: "passed",
        errorMessage: "",
        details: "All checks passed.",
      },
      {
        id: "2",
        recordName: "Contact 2",
        type: "Teams",
        outcome: "review",
        errorMessage: "Missing phone number.",
        details: "Phone number field is empty.",
      },
      {
        id: "3",
        recordName: "Contact 3",
        type: "mine",
        outcome: "error",
        errorMessage: "Invalid email format.",
        details: "Email does not match required pattern.",
      },
    ],
    dateOfRun: "2023-03-15",
    status: "completed",
    breachListLink: "http://example.com/breach-list",
    testedRecordsCount: 100,
    passedRecordsCount: 80,
    failedRecordsCount: 20,
    failedRecordsWithErrorCount: 5,
  },
  {
    id: "1",
    name: "Widget Validate Contacts",
    type: "form",
    breachList: [
      {
        id: "1",
        recordName: "Contact 1",
        type: "mine",
        outcome: "passed",
        errorMessage: "",
        details: "All checks passed.",
      },
      {
        id: "2",
        recordName: "Contact 2",
        type: "Teams",
        outcome: "review",
        errorMessage: "Missing phone number.",
        details: "Phone number field is empty.",
      },
      {
        id: "3",
        recordName: "Contact 3",
        type: "mine",
        outcome: "error",
        errorMessage: "Invalid email format.",
        details: "Email does not match required pattern.",
      },
    ],
    dateOfRun: "2023-03-15",
    status: "completed",
    breachListLink: "http://example.com/breach-list",
    testedRecordsCount: 100,
    passedRecordsCount: 80,
    failedRecordsCount: 20,
    failedRecordsWithErrorCount: 5,
  },
  {
    id: "1",
    name: "Widget Validate Contacts",
    type: "form",
    breachList: [
      {
        id: "1",
        recordName: "Contact 1",
        type: "mine",
        outcome: "passed",
        errorMessage: "",
        details: "All checks passed.",
      },
      {
        id: "2",
        recordName: "Contact 2",
        type: "Teams",
        outcome: "review",
        errorMessage: "Missing phone number.",
        details: "Phone number field is empty.",
      },
      {
        id: "3",
        recordName: "Contact 3",
        type: "mine",
        outcome: "error",
        errorMessage: "Invalid email format.",
        details: "Email does not match required pattern.",
      },
    ],
    dateOfRun: "2023-03-15",
    status: "completed",
    breachListLink: "http://example.com/breach-list",
    testedRecordsCount: 100,
    passedRecordsCount: 80,
    failedRecordsCount: 20,
    failedRecordsWithErrorCount: 5,
  },
  {
    id: "1",
    name: "Widget Validate Contacts",
    type: "form",
    breachList: [
      {
        id: "1",
        recordName: "Contact 1",
        type: "mine",
        outcome: "passed",
        errorMessage: "",
        details: "All checks passed.",
      },
      {
        id: "2",
        recordName: "Contact 2",
        type: "Teams",
        outcome: "review",
        errorMessage: "Missing phone number.",
        details: "Phone number field is empty.",
      },
      {
        id: "3",
        recordName: "Contact 3",
        type: "mine",
        outcome: "error",
        errorMessage: "Invalid email format.",
        details: "Email does not match required pattern.",
      },
    ],
    dateOfRun: "2023-03-15",
    status: "completed",
    breachListLink: "http://example.com/breach-list",
    testedRecordsCount: 100,
    passedRecordsCount: 80,
    failedRecordsCount: 20,
    failedRecordsWithErrorCount: 5,
  },
  {
    id: "1",
    name: "Widget Validate Contacts",
    type: "form",
    breachList: [
      {
        id: "1",
        recordName: "Contact 1",
        type: "mine",
        outcome: "passed",
        errorMessage: "",
        details: "All checks passed.",
      },
      {
        id: "2",
        recordName: "Contact 2",
        type: "Teams",
        outcome: "review",
        errorMessage: "Missing phone number.",
        details: "Phone number field is empty.",
      },
      {
        id: "3",
        recordName: "Contact 3",
        type: "mine",
        outcome: "error",
        errorMessage: "Invalid email format.",
        details: "Email does not match required pattern.",
      },
    ],
    dateOfRun: "2023-03-15",
    status: "completed",
    breachListLink: "http://example.com/breach-list",
    testedRecordsCount: 100,
    passedRecordsCount: 80,
    failedRecordsCount: 20,
    failedRecordsWithErrorCount: 5,
  },
  {
    id: "1",
    name: "Widget Validate Contacts",
    type: "form",
    breachList: [
      {
        id: "1",
        recordName: "Contact 1",
        type: "mine",
        outcome: "passed",
        errorMessage: "",
        details: "All checks passed.",
      },
      {
        id: "2",
        recordName: "Contact 2",
        type: "Teams",
        outcome: "review",
        errorMessage: "Missing phone number.",
        details: "Phone number field is empty.",
      },
      {
        id: "3",
        recordName: "Contact 3",
        type: "mine",
        outcome: "error",
        errorMessage: "Invalid email format.",
        details: "Email does not match required pattern.",
      },
    ],
    dateOfRun: "2023-03-15",
    status: "completed",
    breachListLink: "http://example.com/breach-list",
    testedRecordsCount: 100,
    passedRecordsCount: 80,
    failedRecordsCount: 20,
    failedRecordsWithErrorCount: 5,
  },
  {
    id: "2",
    name: "Widget Validate Documents",
    type: "document",
    breachList: [
      {
        id: "1",
        recordName: "Document 1",
        type: "mine",
        outcome: "passed",
        errorMessage: "",
        details: "Document is valid.",
      },
      {
        id: "2",
        recordName: "Document 2",
        type: "Teams",
        outcome: "review",
        errorMessage: "Signature missing.",
        details: "Document not signed by manager.",
      },
      {
        id: "3",
        recordName: "Document 3",
        type: "mine",
        outcome: "error",
        errorMessage: "Corrupted file.",
        details: "Unable to open document.",
      },
    ],
    dateOfRun: "2023-03-16",
    status: "failed",
    breachListLink: "http://example.com/breach-list-docs",
    testedRecordsCount: 50,
    passedRecordsCount: 30,
    failedRecordsCount: 15,
    failedRecordsWithErrorCount: 5,
  },
  {
    id: "3",
    name: "Widget Validate Onboarding",
    type: "form",
    breachList: [
      {
        id: "1",
        recordName: "Onboarding 1",
        type: "Teams",
        outcome: "passed",
        errorMessage: "",
        details: "All onboarding steps completed.",
      },
      {
        id: "2",
        recordName: "Onboarding 2",
        type: "mine",
        outcome: "review",
        errorMessage: "Photo ID unclear.",
        details: "Photo ID image is blurry.",
      },
      {
        id: "3",
        recordName: "Onboarding 3",
        type: "Teams",
        outcome: "error",
        errorMessage: "Background check failed.",
        details: "Candidate did not pass background check.",
      },
    ],
    dateOfRun: "2023-03-17",
    status: "running",
    breachListLink: "http://example.com/breach-list-onboarding",
    testedRecordsCount: 75,
    passedRecordsCount: 50,
    failedRecordsCount: 20,
    failedRecordsWithErrorCount: 5,
  },
  {
    id: "4",
    name: "Widget Validate Compliance",
    type: "document",
    breachList: [
      {
        id: "1",
        recordName: "Compliance 1",
        type: "mine",
        outcome: "passed",
        errorMessage: "",
        details: "Compliant with all standards.",
      },
      {
        id: "2",
        recordName: "Compliance 2",
        type: "Teams",
        outcome: "review",
        errorMessage: "Policy update required.",
        details: "Policy outdated, needs review.",
      },
      {
        id: "3",
        recordName: "Compliance 3",
        type: "mine",
        outcome: "error",
        errorMessage: "Non-compliance detected.",
        details: "Failed compliance check for section 4.",
      },
    ],
    dateOfRun: "2023-03-18",
    status: "completed",
    breachListLink: "http://example.com/breach-list-compliance",
    testedRecordsCount: 120,
    passedRecordsCount: 100,
    failedRecordsCount: 15,
    failedRecordsWithErrorCount: 5,
  },
];
